version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - dist/*
    - dist/static/*
    - dist/static/js/*
    - dist/static/img/*
    - dist/static/fonts/*
    - dist/static/css/*
